// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAleOYSw_bQDHvOaJNkPtPPUvz4TUOvFHQ',
    appId: '1:619786440642:web:e6346a319faa1fec34105b',
    messagingSenderId: '619786440642',
    projectId: 'videocall-f25a3',
    authDomain: 'videocall-f25a3.firebaseapp.com',
    storageBucket: 'videocall-f25a3.firebasestorage.app',
    measurementId: 'G-SDKJF9KNKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcOx77rSyhoRsKGJI5WG_vYhAdZ076_HM',
    appId: '1:619786440642:android:ab1bbed7a3ba2d8534105b',
    messagingSenderId: '619786440642',
    projectId: 'videocall-f25a3',
    storageBucket: 'videocall-f25a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWHqNqHHyFOOpM1iK5n9d11UzLFK4jRlw',
    appId: '1:619786440642:ios:230fa90238af678f34105b',
    messagingSenderId: '619786440642',
    projectId: 'videocall-f25a3',
    storageBucket: 'videocall-f25a3.firebasestorage.app',
    iosBundleId: 'com.example.videoCall',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWHqNqHHyFOOpM1iK5n9d11UzLFK4jRlw',
    appId: '1:619786440642:ios:230fa90238af678f34105b',
    messagingSenderId: '619786440642',
    projectId: 'videocall-f25a3',
    storageBucket: 'videocall-f25a3.firebasestorage.app',
    iosBundleId: 'com.example.videoCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAleOYSw_bQDHvOaJNkPtPPUvz4TUOvFHQ',
    appId: '1:619786440642:web:50a11a3dcb26e7af34105b',
    messagingSenderId: '619786440642',
    projectId: 'videocall-f25a3',
    authDomain: 'videocall-f25a3.firebaseapp.com',
    storageBucket: 'videocall-f25a3.firebasestorage.app',
    measurementId: 'G-JTL7W1J207',
  );
}
